[package]
name = "kata-agent"
version = "0.1.0"
authors = ["Yang Bo <bo@hyper.sh>"]
edition = "2018"

[dependencies]
oci = { path = "oci" }
libcontainer = { path = "libcontainer" }
lazy_static = "1.3.0"
error-chain = "0.12.1"
