[package]
name = "libcontainer"
version = "0.1.0"
authors = ["Yang Bo <bo@hyper.sh>"]
edition = "2018"

[dependencies]
error_chain = "0.12.1"
serde = "1.0.91"
serde_json = "1.0.91"
serde_derive = "1.0.91"
oci = { path = "../oci" }
caps = "0.3.0"
nix = "0.14.0"

[build-dependencies]
cc = "1.0.37"
